### ISSUE TITLE
[question] regarding deep population

### ISSUE THREAD

**Issue by japel** [arvitaly/sails-graphql-adapter#11]
Hey there!
Nice work by now!

Would this adapter take care of deep population of objects?

Best regards

japel

**Comment by arvitaly** [comment]
Hi!
Yes, adapter will support all the graphql abilities, and support the live-queries (by websockets).

**Comment by japel** [comment]
Ok, thanks for the quick answer... So there seem to be a problem in my models... I can't get passed one level of deepness. Just testing it with localDiskDb

**Comment by japel** [comment]
besides that, have you tried this adapter with a 1.0.x version of sails?

**Comment by arvitaly** [comment]
Sorry, now this repo is in VERY active development, so, i think, you should wait for few days for testing it :-)

**Comment by japel** [comment]
@arvitaly I see! :) let me know if I can help with anything... Seems like a very elegant approach to reuse sails models...
